"""add_faturas_pagar_table

Revision ID: 2c144ff50a13
Revises: c010b395b9c8
Create Date: 2025-11-07 12:52:45.266231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c144ff50a13'
down_revision: Union[str, None] = 'c010b395b9c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faturas_pagar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filial_id', sa.Integer(), nullable=False),
    sa.Column('filial_nome', sa.String(length=255), nullable=False),
    sa.Column('numero_ap', sa.String(length=50), nullable=False),
    sa.Column('numero_parcela', sa.String(length=50), nullable=False),
    sa.Column('tipo_documento', sa.String(length=100), nullable=False),
    sa.Column('numero_documento', sa.String(length=100), nullable=True),
    sa.Column('valor_parcela', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('saldo_atual', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_baixa', sa.Date(), nullable=True),
    sa.Column('agente_codigo', sa.Integer(), nullable=True),
    sa.Column('agente_nome', sa.String(length=255), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_ap', 'numero_parcela', name='uq_fatura_ap_parcela')
    )
    op.create_index('idx_fatura_filial_baixa', 'faturas_pagar', ['filial_id', 'data_baixa'], unique=False)
    op.create_index('idx_fatura_filial_vencimento', 'faturas_pagar', ['filial_id', 'data_vencimento'], unique=False)
    op.create_index('idx_fatura_tipo_documento', 'faturas_pagar', ['tipo_documento'], unique=False)
    op.create_index(op.f('ix_faturas_pagar_data_baixa'), 'faturas_pagar', ['data_baixa'], unique=False)
    op.create_index(op.f('ix_faturas_pagar_data_vencimento'), 'faturas_pagar', ['data_vencimento'], unique=False)
    op.create_index(op.f('ix_faturas_pagar_filial_id'), 'faturas_pagar', ['filial_id'], unique=False)
    op.drop_constraint(op.f('fk_balance_development'), 'balance', type_='foreignkey')
    op.drop_constraint(op.f('fk_cash_in_development'), 'cash_in', type_='foreignkey')
    op.drop_constraint(op.f('fk_cash_out_development'), 'cash_out', type_='foreignkey')
    op.drop_index(op.f('ix_contracts_cod_empreendimento'), table_name='contracts')
    op.create_index(op.f('ix_contracts_empreendimento_id'), 'contracts', ['empreendimento_id'], unique=False)
    op.drop_constraint(op.f('fk_contracts_development'), 'contracts', type_='foreignkey')
    op.drop_index(op.f('ix_delinquency_ref_date'), table_name='delinquency')
    op.create_index(op.f('ix_delinquency_ref_month'), 'delinquency', ['ref_month'], unique=False)
    op.drop_constraint(op.f('fk_portfolio_stats_development'), 'portfolio_stats', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_portfolio_stats_development'), 'portfolio_stats', 'developments', ['empreendimento_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_delinquency_ref_month'), table_name='delinquency')
    op.create_index(op.f('ix_delinquency_ref_date'), 'delinquency', ['ref_month'], unique=False)
    op.create_foreign_key(op.f('fk_contracts_development'), 'contracts', 'developments', ['empreendimento_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_contracts_empreendimento_id'), table_name='contracts')
    op.create_index(op.f('ix_contracts_cod_empreendimento'), 'contracts', ['empreendimento_id'], unique=False)
    op.create_foreign_key(op.f('fk_cash_out_development'), 'cash_out', 'developments', ['empreendimento_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_cash_in_development'), 'cash_in', 'developments', ['empreendimento_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_balance_development'), 'balance', 'developments', ['empreendimento_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_faturas_pagar_filial_id'), table_name='faturas_pagar')
    op.drop_index(op.f('ix_faturas_pagar_data_vencimento'), table_name='faturas_pagar')
    op.drop_index(op.f('ix_faturas_pagar_data_baixa'), table_name='faturas_pagar')
    op.drop_index('idx_fatura_tipo_documento', table_name='faturas_pagar')
    op.drop_index('idx_fatura_filial_vencimento', table_name='faturas_pagar')
    op.drop_index('idx_fatura_filial_baixa', table_name='faturas_pagar')
    op.drop_table('faturas_pagar')
    # ### end Alembic commands ###
