"""Initial schema - create all tables

Revision ID: 340a53c7fde5
Revises: 
Create Date: 2025-10-22 14:15:38.166873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340a53c7fde5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empreendimento_id', sa.Integer(), nullable=False),
    sa.Column('empreendimento_nome', sa.String(length=200), nullable=False),
    sa.Column('ref_date', sa.String(length=10), nullable=False),
    sa.Column('opening', sa.Float(), nullable=False),
    sa.Column('closing', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empreendimento_id', 'ref_date', name='uq_balance_emp_date')
    )
    op.create_index('idx_balance_emp_ref_date', 'balance', ['empreendimento_id', 'ref_date'], unique=False)
    op.create_index(op.f('ix_balance_empreendimento_id'), 'balance', ['empreendimento_id'], unique=False)
    op.create_index(op.f('ix_balance_ref_date'), 'balance', ['ref_date'], unique=False)
    op.create_table('cash_in',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empreendimento_id', sa.Integer(), nullable=False),
    sa.Column('empreendimento_nome', sa.String(length=200), nullable=False),
    sa.Column('ref_date', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('forecast', sa.Float(), nullable=False),
    sa.Column('actual', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cash_in_emp_ref_date', 'cash_in', ['empreendimento_id', 'ref_date'], unique=False)
    op.create_index('idx_cash_in_ref_date_category', 'cash_in', ['ref_date', 'category'], unique=False)
    op.create_index(op.f('ix_cash_in_empreendimento_id'), 'cash_in', ['empreendimento_id'], unique=False)
    op.create_index(op.f('ix_cash_in_ref_date'), 'cash_in', ['ref_date'], unique=False)
    op.create_table('cash_out',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empreendimento_id', sa.Integer(), nullable=False),
    sa.Column('empreendimento_nome', sa.String(length=200), nullable=False),
    sa.Column('ref_date', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('actual', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cash_out_emp_ref_date', 'cash_out', ['empreendimento_id', 'ref_date'], unique=False)
    op.create_index('idx_cash_out_ref_date_category', 'cash_out', ['ref_date', 'category'], unique=False)
    op.create_index(op.f('ix_cash_out_empreendimento_id'), 'cash_out', ['empreendimento_id'], unique=False)
    op.create_index(op.f('ix_cash_out_ref_date'), 'cash_out', ['ref_date'], unique=False)
    op.create_table('portfolio_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empreendimento_id', sa.Integer(), nullable=False),
    sa.Column('empreendimento_nome', sa.String(length=200), nullable=False),
    sa.Column('ref_date', sa.String(length=10), nullable=False),
    sa.Column('vp', sa.Float(), nullable=False),
    sa.Column('ltv', sa.Float(), nullable=False),
    sa.Column('prazo_medio', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('total_contracts', sa.Integer(), nullable=False),
    sa.Column('active_contracts', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empreendimento_id', 'ref_date', name='uq_portfolio_emp_date')
    )
    op.create_index('idx_portfolio_emp_ref_date', 'portfolio_stats', ['empreendimento_id', 'ref_date'], unique=False)
    op.create_index(op.f('ix_portfolio_stats_empreendimento_id'), 'portfolio_stats', ['empreendimento_id'], unique=False)
    op.create_index(op.f('ix_portfolio_stats_ref_date'), 'portfolio_stats', ['ref_date'], unique=False)
    op.create_table('raw_payloads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('exec_date', sa.String(length=10), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'exec_date', 'payload_hash', name='uq_payload_idempotency')
    )
    op.create_index('idx_source_exec_date', 'raw_payloads', ['source', 'exec_date'], unique=False)
    op.create_index(op.f('ix_raw_payloads_exec_date'), 'raw_payloads', ['exec_date'], unique=False)
    op.create_index(op.f('ix_raw_payloads_source'), 'raw_payloads', ['source'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exec_date', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exec_date_status', 'runs', ['exec_date', 'status'], unique=False)
    op.create_index(op.f('ix_runs_exec_date'), 'runs', ['exec_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_exec_date'), table_name='runs')
    op.drop_index('idx_exec_date_status', table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_raw_payloads_source'), table_name='raw_payloads')
    op.drop_index(op.f('ix_raw_payloads_exec_date'), table_name='raw_payloads')
    op.drop_index('idx_source_exec_date', table_name='raw_payloads')
    op.drop_table('raw_payloads')
    op.drop_index(op.f('ix_portfolio_stats_ref_date'), table_name='portfolio_stats')
    op.drop_index(op.f('ix_portfolio_stats_empreendimento_id'), table_name='portfolio_stats')
    op.drop_index('idx_portfolio_emp_ref_date', table_name='portfolio_stats')
    op.drop_table('portfolio_stats')
    op.drop_index(op.f('ix_cash_out_ref_date'), table_name='cash_out')
    op.drop_index(op.f('ix_cash_out_empreendimento_id'), table_name='cash_out')
    op.drop_index('idx_cash_out_ref_date_category', table_name='cash_out')
    op.drop_index('idx_cash_out_emp_ref_date', table_name='cash_out')
    op.drop_table('cash_out')
    op.drop_index(op.f('ix_cash_in_ref_date'), table_name='cash_in')
    op.drop_index(op.f('ix_cash_in_empreendimento_id'), table_name='cash_in')
    op.drop_index('idx_cash_in_ref_date_category', table_name='cash_in')
    op.drop_index('idx_cash_in_emp_ref_date', table_name='cash_in')
    op.drop_table('cash_in')
    op.drop_index(op.f('ix_balance_ref_date'), table_name='balance')
    op.drop_index(op.f('ix_balance_empreendimento_id'), table_name='balance')
    op.drop_index('idx_balance_emp_ref_date', table_name='balance')
    op.drop_table('balance')
    # ### end Alembic commands ###
