"""Add monthly aggregation tables for performance optimization

Revision ID: 5e40ad330e8d
Revises: 7954174509a7
Create Date: 2025-10-23 16:42:28.349126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e40ad330e8d'
down_revision: Union[str, None] = '7954174509a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_balance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empreendimento_id', sa.Integer(), nullable=False),
    sa.Column('empreendimento_nome', sa.String(length=200), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('opening_balance', sa.Float(), nullable=False),
    sa.Column('closing_balance', sa.Float(), nullable=False),
    sa.Column('min_balance', sa.Float(), nullable=False),
    sa.Column('max_balance', sa.Float(), nullable=False),
    sa.Column('avg_balance', sa.Float(), nullable=False),
    sa.Column('first_day', sa.String(length=10), nullable=False),
    sa.Column('last_day', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empreendimento_id', 'year_month', name='uq_monthly_balance_emp_month')
    )
    op.create_index('idx_monthly_balance_emp_month', 'monthly_balance', ['empreendimento_id', 'year_month'], unique=False)
    op.create_index('idx_monthly_balance_year_month', 'monthly_balance', ['year_month'], unique=False)
    op.create_index(op.f('ix_monthly_balance_empreendimento_id'), 'monthly_balance', ['empreendimento_id'], unique=False)
    op.create_index(op.f('ix_monthly_balance_year_month'), 'monthly_balance', ['year_month'], unique=False)
    op.create_table('monthly_cash_flow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empreendimento_id', sa.Integer(), nullable=False),
    sa.Column('empreendimento_nome', sa.String(length=200), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('cash_in_ativos_forecast', sa.Float(), nullable=False),
    sa.Column('cash_in_ativos_actual', sa.Float(), nullable=False),
    sa.Column('cash_in_recuperacoes_forecast', sa.Float(), nullable=False),
    sa.Column('cash_in_recuperacoes_actual', sa.Float(), nullable=False),
    sa.Column('cash_in_antecipacoes_forecast', sa.Float(), nullable=False),
    sa.Column('cash_in_antecipacoes_actual', sa.Float(), nullable=False),
    sa.Column('cash_in_outras_forecast', sa.Float(), nullable=False),
    sa.Column('cash_in_outras_actual', sa.Float(), nullable=False),
    sa.Column('cash_in_total_forecast', sa.Float(), nullable=False),
    sa.Column('cash_in_total_actual', sa.Float(), nullable=False),
    sa.Column('cash_out_opex_budget', sa.Float(), nullable=False),
    sa.Column('cash_out_opex_actual', sa.Float(), nullable=False),
    sa.Column('cash_out_financeiras_budget', sa.Float(), nullable=False),
    sa.Column('cash_out_financeiras_actual', sa.Float(), nullable=False),
    sa.Column('cash_out_capex_budget', sa.Float(), nullable=False),
    sa.Column('cash_out_capex_actual', sa.Float(), nullable=False),
    sa.Column('cash_out_distribuicoes_budget', sa.Float(), nullable=False),
    sa.Column('cash_out_distribuicoes_actual', sa.Float(), nullable=False),
    sa.Column('cash_out_total_budget', sa.Float(), nullable=False),
    sa.Column('cash_out_total_actual', sa.Float(), nullable=False),
    sa.Column('net_flow', sa.Float(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('first_day', sa.String(length=10), nullable=False),
    sa.Column('last_day', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empreendimento_id', 'year_month', name='uq_monthly_cashflow_emp_month')
    )
    op.create_index('idx_monthly_cashflow_emp_month', 'monthly_cash_flow', ['empreendimento_id', 'year_month'], unique=False)
    op.create_index('idx_monthly_cashflow_year_month', 'monthly_cash_flow', ['year_month'], unique=False)
    op.create_index(op.f('ix_monthly_cash_flow_empreendimento_id'), 'monthly_cash_flow', ['empreendimento_id'], unique=False)
    op.create_index(op.f('ix_monthly_cash_flow_year_month'), 'monthly_cash_flow', ['year_month'], unique=False)
    op.create_table('monthly_delinquency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empreendimento_id', sa.Integer(), nullable=False),
    sa.Column('empreendimento_nome', sa.String(length=200), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('up_to_30', sa.Float(), nullable=False),
    sa.Column('days_30_60', sa.Float(), nullable=False),
    sa.Column('days_60_90', sa.Float(), nullable=False),
    sa.Column('days_90_180', sa.Float(), nullable=False),
    sa.Column('above_180', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empreendimento_id', 'year_month', name='uq_monthly_delinquency_emp_month')
    )
    op.create_index('idx_monthly_delinquency_emp_month', 'monthly_delinquency', ['empreendimento_id', 'year_month'], unique=False)
    op.create_index('idx_monthly_delinquency_year_month', 'monthly_delinquency', ['year_month'], unique=False)
    op.create_index(op.f('ix_monthly_delinquency_empreendimento_id'), 'monthly_delinquency', ['empreendimento_id'], unique=False)
    op.create_index(op.f('ix_monthly_delinquency_year_month'), 'monthly_delinquency', ['year_month'], unique=False)
    op.create_table('monthly_portfolio_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empreendimento_id', sa.Integer(), nullable=False),
    sa.Column('empreendimento_nome', sa.String(length=200), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('vp', sa.Float(), nullable=False),
    sa.Column('ltv', sa.Float(), nullable=False),
    sa.Column('prazo_medio', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('total_contracts', sa.Integer(), nullable=False),
    sa.Column('active_contracts', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empreendimento_id', 'year_month', name='uq_monthly_portfolio_emp_month')
    )
    op.create_index('idx_monthly_portfolio_emp_month', 'monthly_portfolio_stats', ['empreendimento_id', 'year_month'], unique=False)
    op.create_index('idx_monthly_portfolio_year_month', 'monthly_portfolio_stats', ['year_month'], unique=False)
    op.create_index(op.f('ix_monthly_portfolio_stats_empreendimento_id'), 'monthly_portfolio_stats', ['empreendimento_id'], unique=False)
    op.create_index(op.f('ix_monthly_portfolio_stats_year_month'), 'monthly_portfolio_stats', ['year_month'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_portfolio_stats_year_month'), table_name='monthly_portfolio_stats')
    op.drop_index(op.f('ix_monthly_portfolio_stats_empreendimento_id'), table_name='monthly_portfolio_stats')
    op.drop_index('idx_monthly_portfolio_year_month', table_name='monthly_portfolio_stats')
    op.drop_index('idx_monthly_portfolio_emp_month', table_name='monthly_portfolio_stats')
    op.drop_table('monthly_portfolio_stats')
    op.drop_index(op.f('ix_monthly_delinquency_year_month'), table_name='monthly_delinquency')
    op.drop_index(op.f('ix_monthly_delinquency_empreendimento_id'), table_name='monthly_delinquency')
    op.drop_index('idx_monthly_delinquency_year_month', table_name='monthly_delinquency')
    op.drop_index('idx_monthly_delinquency_emp_month', table_name='monthly_delinquency')
    op.drop_table('monthly_delinquency')
    op.drop_index(op.f('ix_monthly_cash_flow_year_month'), table_name='monthly_cash_flow')
    op.drop_index(op.f('ix_monthly_cash_flow_empreendimento_id'), table_name='monthly_cash_flow')
    op.drop_index('idx_monthly_cashflow_year_month', table_name='monthly_cash_flow')
    op.drop_index('idx_monthly_cashflow_emp_month', table_name='monthly_cash_flow')
    op.drop_table('monthly_cash_flow')
    op.drop_index(op.f('ix_monthly_balance_year_month'), table_name='monthly_balance')
    op.drop_index(op.f('ix_monthly_balance_empreendimento_id'), table_name='monthly_balance')
    op.drop_index('idx_monthly_balance_year_month', table_name='monthly_balance')
    op.drop_index('idx_monthly_balance_emp_month', table_name='monthly_balance')
    op.drop_table('monthly_balance')
    # ### end Alembic commands ###
