"""add_users_and_email_recipients_tables

Revision ID: 6c52ad66450a
Revises: 340a53c7fde5
Create Date: 2025-10-22 15:38:09.392318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c52ad66450a'
down_revision: Union[str, None] = '340a53c7fde5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_recipients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('empreendimento_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'empreendimento_id', name='uq_recipient_email_emp')
    )
    op.create_index('idx_recipient_active', 'email_recipients', ['is_active'], unique=False)
    op.create_index('idx_recipient_emp', 'email_recipients', ['empreendimento_id'], unique=False)
    op.create_index(op.f('ix_email_recipients_email'), 'email_recipients', ['email'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_email_recipients_email'), table_name='email_recipients')
    op.drop_index('idx_recipient_emp', table_name='email_recipients')
    op.drop_index('idx_recipient_active', table_name='email_recipients')
    op.drop_table('email_recipients')
    # ### end Alembic commands ###
