"""Add delinquency table

Revision ID: 7954174509a7
Revises: 642ac9120e4f
Create Date: 2025-10-23 16:07:21.606294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7954174509a7'
down_revision: Union[str, None] = '642ac9120e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delinquency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empreendimento_id', sa.Integer(), nullable=False),
    sa.Column('empreendimento_nome', sa.String(length=200), nullable=False),
    sa.Column('ref_date', sa.String(length=10), nullable=False),
    sa.Column('up_to_30', sa.Float(), nullable=False),
    sa.Column('days_30_60', sa.Float(), nullable=False),
    sa.Column('days_60_90', sa.Float(), nullable=False),
    sa.Column('days_90_180', sa.Float(), nullable=False),
    sa.Column('above_180', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empreendimento_id', 'ref_date', name='uq_delinquency_emp_date')
    )
    op.create_index('idx_delinquency_emp_ref_date', 'delinquency', ['empreendimento_id', 'ref_date'], unique=False)
    op.create_index(op.f('ix_delinquency_empreendimento_id'), 'delinquency', ['empreendimento_id'], unique=False)
    op.create_index(op.f('ix_delinquency_ref_date'), 'delinquency', ['ref_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delinquency_ref_date'), table_name='delinquency')
    op.drop_index(op.f('ix_delinquency_empreendimento_id'), table_name='delinquency')
    op.drop_index('idx_delinquency_emp_ref_date', table_name='delinquency')
    op.drop_table('delinquency')
    # ### end Alembic commands ###
