"""add_centro_custo_id_to_developments

Revision ID: 86a4972809a4
Revises: 0029455cfa5f
Create Date: 2025-10-24 14:36:01.163255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a4972809a4'
down_revision: Union[str, None] = '0029455cfa5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('balance', 'ref_month',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=7),
               existing_nullable=False)
    op.drop_index(op.f('ix_balance_ref_date'), table_name='balance')
    op.create_index(op.f('ix_balance_ref_month'), 'balance', ['ref_month'], unique=False)
    op.alter_column('cash_in', 'ref_month',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=7),
               existing_nullable=False)
    op.drop_index(op.f('ix_cash_in_ref_date'), table_name='cash_in')
    op.create_index(op.f('ix_cash_in_ref_month'), 'cash_in', ['ref_month'], unique=False)
    op.alter_column('cash_out', 'ref_month',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=7),
               existing_nullable=False)
    op.drop_index(op.f('ix_cash_out_ref_date'), table_name='cash_out')
    op.create_index(op.f('ix_cash_out_ref_month'), 'cash_out', ['ref_month'], unique=False)
    op.add_column('developments', sa.Column('centro_custo_id', sa.Integer(), nullable=True))
    op.create_index('idx_development_centro_custo', 'developments', ['centro_custo_id'], unique=False)
    op.create_index(op.f('ix_developments_centro_custo_id'), 'developments', ['centro_custo_id'], unique=False)
    op.alter_column('portfolio_stats', 'ref_month',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=7),
               existing_nullable=False)
    op.drop_index(op.f('ix_portfolio_stats_ref_date'), table_name='portfolio_stats')
    op.create_index(op.f('ix_portfolio_stats_ref_month'), 'portfolio_stats', ['ref_month'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_stats_ref_month'), table_name='portfolio_stats')
    op.create_index(op.f('ix_portfolio_stats_ref_date'), 'portfolio_stats', ['ref_month'], unique=False)
    op.alter_column('portfolio_stats', 'ref_month',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_developments_centro_custo_id'), table_name='developments')
    op.drop_index('idx_development_centro_custo', table_name='developments')
    op.drop_column('developments', 'centro_custo_id')
    op.drop_index(op.f('ix_cash_out_ref_month'), table_name='cash_out')
    op.create_index(op.f('ix_cash_out_ref_date'), 'cash_out', ['ref_month'], unique=False)
    op.alter_column('cash_out', 'ref_month',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_cash_in_ref_month'), table_name='cash_in')
    op.create_index(op.f('ix_cash_in_ref_date'), 'cash_in', ['ref_month'], unique=False)
    op.alter_column('cash_in', 'ref_month',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_balance_ref_month'), table_name='balance')
    op.create_index(op.f('ix_balance_ref_date'), 'balance', ['ref_month'], unique=False)
    op.alter_column('balance', 'ref_month',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
