"""Add sync audit tables (runs and raw_payloads)

Revision ID: 89992e171a45
Revises: 5e40ad330e8d
Create Date: 2025-10-23 18:53:26.780833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89992e171a45'
down_revision: Union[str, None] = '5e40ad330e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
