"""add_contracts_table

Revision ID: a4c7d57536d8
Revises: 86a4972809a4
Create Date: 2025-10-30 13:04:57.134344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4c7d57536d8'
down_revision: Union[str, None] = '86a4972809a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cod_contrato', sa.Integer(), nullable=False),
    sa.Column('cod_empreendimento', sa.Integer(), nullable=False),
    sa.Column('nome_empreendimento', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('cod_cliente', sa.Integer(), nullable=True),
    sa.Column('nome_cliente', sa.String(length=255), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=True),
    sa.Column('data_contrato', sa.String(length=10), nullable=True),
    sa.Column('valor_contrato', sa.Float(), nullable=False),
    sa.Column('saldo_devedor', sa.Float(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod_contrato', 'cod_empreendimento', name='uq_contract_cod_emp')
    )
    op.create_index('idx_contract_emp_status', 'contracts', ['cod_empreendimento', 'status'], unique=False)
    op.create_index('idx_contract_status', 'contracts', ['status'], unique=False)
    op.create_index(op.f('ix_contracts_cod_contrato'), 'contracts', ['cod_contrato'], unique=False)
    op.create_index(op.f('ix_contracts_cod_empreendimento'), 'contracts', ['cod_empreendimento'], unique=False)
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_cod_empreendimento'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_cod_contrato'), table_name='contracts')
    op.drop_index('idx_contract_status', table_name='contracts')
    op.drop_index('idx_contract_emp_status', table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
