"""Add report access tokens table

Revision ID: c1e8eb887fc2
Revises: 36ef5216c9de
Create Date: 2025-10-22 18:33:21.637661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e8eb887fc2'
down_revision: Union[str, None] = '36ef5216c9de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_access_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('empreendimento_id', sa.Integer(), nullable=False),
    sa.Column('ref_date', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_emp_date', 'report_access_tokens', ['empreendimento_id', 'ref_date'], unique=False)
    op.create_index('idx_token_exp', 'report_access_tokens', ['token', 'expires_at'], unique=False)
    op.create_index(op.f('ix_report_access_tokens_empreendimento_id'), 'report_access_tokens', ['empreendimento_id'], unique=False)
    op.create_index(op.f('ix_report_access_tokens_expires_at'), 'report_access_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_report_access_tokens_ref_date'), 'report_access_tokens', ['ref_date'], unique=False)
    op.create_index(op.f('ix_report_access_tokens_token'), 'report_access_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_access_tokens_token'), table_name='report_access_tokens')
    op.drop_index(op.f('ix_report_access_tokens_ref_date'), table_name='report_access_tokens')
    op.drop_index(op.f('ix_report_access_tokens_expires_at'), table_name='report_access_tokens')
    op.drop_index(op.f('ix_report_access_tokens_empreendimento_id'), table_name='report_access_tokens')
    op.drop_index('idx_token_exp', table_name='report_access_tokens')
    op.drop_index('idx_emp_date', table_name='report_access_tokens')
    op.drop_table('report_access_tokens')
    # ### end Alembic commands ###
