"""Add recipient tracking to access tokens

Revision ID: c95c4bb14c77
Revises: c1e8eb887fc2
Create Date: 2025-10-22 18:36:10.119346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c95c4bb14c77'
down_revision: Union[str, None] = 'c1e8eb887fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_access_tokens', sa.Column('recipient_email', sa.String(length=255), nullable=True))
    op.add_column('report_access_tokens', sa.Column('recipient_name', sa.String(length=255), nullable=True))
    op.create_index('idx_recipient', 'report_access_tokens', ['recipient_email'], unique=False)
    op.create_index(op.f('ix_report_access_tokens_recipient_email'), 'report_access_tokens', ['recipient_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_access_tokens_recipient_email'), table_name='report_access_tokens')
    op.drop_index('idx_recipient', table_name='report_access_tokens')
    op.drop_column('report_access_tokens', 'recipient_name')
    op.drop_column('report_access_tokens', 'recipient_email')
    # ### end Alembic commands ###
