"""simplify_contracts_table_keep_only_essential_fields

Revision ID: d43246ea9abe
Revises: a4c7d57536d8
Create Date: 2025-10-30 13:16:08.385314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd43246ea9abe'
down_revision: Union[str, None] = 'a4c7d57536d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'cpf_cnpj')
    op.drop_column('contracts', 'valor_contrato')
    op.drop_column('contracts', 'data_contrato')
    op.drop_column('contracts', 'created_at')
    op.drop_column('contracts', 'saldo_devedor')
    op.drop_column('contracts', 'raw_data')
    op.drop_column('contracts', 'cod_cliente')
    op.drop_column('contracts', 'nome_cliente')
    op.drop_column('contracts', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('nome_cliente', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('cod_cliente', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('saldo_devedor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('contracts', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('contracts', sa.Column('data_contrato', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('valor_contrato', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('contracts', sa.Column('cpf_cnpj', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
